services:
  - type: worker
    name: darkxxweb-bot-service
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
