services:
  - type: web
    name: darkxxweb-bot-service
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node start.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
